export const metadata = {
  title: "Create Next App",
  description: "Generated by Sungsik Kim",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
